### ISSUE TITLE
审批动作点击编辑填写的内容没有显示

### ISSUE THREAD

**Issue by lihang212010** [longguikeji/arkid#1120]
审批动作点击编辑填写的内容没有显
![截图 2022-08-01 17-29-42](https://user-images.githubusercontent.com/38468839/182118715-0a362952-a8eb-4930-902d-bab087477b74.png)
![截图 2022-08-01 17-29-49](https://user-images.githubusercontent.com/38468839/182118723-d93ead5d-77be-4432-91eb-0fd255a90969.png)
示

**Comment by fanhe-lg** [comment]
已修复
