### ISSUE TITLE
审批系统有个空字不能编辑

### ISSUE THREAD

**Issue by lihang212010** [longguikeji/arkid#1121]
审批系统有个空字
![image](https://user-images.githubusercontent.com/38468839/182120951-ece5644c-470c-4f94-bfe0-fbdb5c71ad93.png)

**Comment by fanhe-lg** [comment]
这个是只读的配置，不能编辑的，创建之后会返回一个链接

**Comment by fanhe-lg** [comment]
有些配置是只读的，点击确认之后会返回只读的内容
