### ISSUE TITLE
能否展示用户的所有权限

### ISSUE THREAD

**Issue by lihang212010** [longguikeji/arkid#1125]
我在分组中的权限不能在用户中展示，是否可以在界面展示用户的所有权限
![image](https://user-images.githubusercontent.com/38468839/182287561-eefe0b59-b494-4bba-8985-bdc22caac6fe.png)
![image](https://user-images.githubusercontent.com/38468839/182287590-9ac27490-b73d-462e-a43a-adc5bf96bfbf.png)

**Comment by hanbinloop** [comment]
你好，感谢您的反馈，此BUG已在[feature-402](https://github.com/longguikeji/arkid/tree/feature-402)分支修复，并已合并至[v2.5-dev](https://github.com/longguikeji/arkid/tree/v2.5-dev)。请拉取最新代码，再次感谢指正。

**Comment by hanbinloop** [comment]
![image](https://user-images.githubusercontent.com/16644654/184053492-6546f84a-95a9-4a1d-ba09-bfc1a6037de1.png)

**Comment by hanbinloop** [comment]
![image](https://user-images.githubusercontent.com/16644654/184054352-508b4e5b-e7bb-4697-9be4-d7382c421783.png)
