### ISSUE TITLE
点击切换语言报错

### ISSUE THREAD

**Issue by zhs95** [longguikeji/arkid#1151]
![image](https://user-images.githubusercontent.com/24802455/183599341-f8f86d9c-855e-46b5-a4fc-8eaed40a604b.png)

**Comment by longgui-penglei** [comment]
您好，感谢您的反馈。此BUG已在前端修复，并已合并至前端[v2.5-dev](https://github.com/longguikeji/arkid-frontend-vue3/tree/v2.5-dev)和[main](https://github.com/longguikeji/arkid-frontend-vue3)分支，请拉取最新代码，再次感谢指正。
