### ISSUE TITLE
平台配置Arkid访问地址没有做地址校验并且保存不弹出保存成功

### ISSUE THREAD

**Issue by lihang212010** [longguikeji/arkid#1171]
平台配置Arkid访问地址没有做地址校验并且保存不弹出保存成功，导致点击确定后在此访问会导致无限循环
![image](https://user-images.githubusercontent.com/38468839/184599529-73180620-a92c-4dbb-af26-73ef1fb4e944.png)

**Comment by longgui-penglei** [comment]
您好，感谢您的反馈。此BUG（循环）已在前端修复，并已合并至前端[v2.5-dev](https://github.com/longguikeji/arkid-frontend-vue3/tree/v2.5-dev)分支，请拉取最新代码，再次感谢指正。
