### ISSUE TITLE
SCIM同步服务器创建中点击设置无法关闭弹窗

### ISSUE THREAD

**Issue by lihang212010** [longguikeji/arkid#1173]
SCIM同步服务器创建中点击设置无法关闭弹窗
![image](https://user-images.githubusercontent.com/38468839/184603380-5793a1ff-b79b-4915-b429-6e525fb6e1c9.png)
![image](https://user-images.githubusercontent.com/38468839/184603405-d910462f-d784-4f2e-95ab-ba0220ef78b8.png)
![image](https://user-images.githubusercontent.com/38468839/184603452-559a8a1a-faf9-4e5e-94e7-0241ce906180.png)
这个表头设置无法关闭

**Comment by longgui-penglei** [comment]
您好，感谢您的反馈。此BUG已在前端修复，并已合并至前端[v2.5-dev](https://github.com/longguikeji/arkid-frontend-vue3/tree/v2.5-dev)和[main](https://github.com/longguikeji/arkid-frontend-vue3)分支，请拉取最新代码，再次感谢指正。
