### ISSUE TITLE
第三方接入应用怎么调用系统的API，如获取用户手机号码

### ISSUE THREAD

**Issue by CtrlAndZ** [longguikeji/arkid#1471]
例如我一个第三方应用接入到系统
在应用列表中添加了一个应用，应用选择oidc授权方式
我得到了client_id，client_secret，和一个接口调用密钥
我通过授权url得到code，再用code换取access_token
使用access_token通过userinfo接口我得到了用户的租户编号和用户编号

然后我的目的是获取用户手机号码，于是我在 扩展能力 -> api文档中找到了get user(/api/v1/tenant/{tenant_id}/users/{id}/)这个接口，在文档中显示可以获取用户手机号码

但是我使用用户的access_token去调用返回的是"detail": "Unauthorized"

应用已经授权该接口

**Comment by welylongguikeji** [comment]
<img width="943" alt="image" src="https://user-images.githubusercontent.com/46774210/211779889-5397b437-0734-4398-8dc1-b6d49ba6749e.png">

参考下这个接口。

这里需要解释一下，OIDC授权的token是用户的token，而非应用的。所以，如果你想要让用户访问 get user(/api/v1/tenant/{tenant_id}/users/{id}/)这个接口的话，需要授权给用户而非应用，授权给应用是没用的。

给应用授予权限，是要通过以应用的身份去访问ArkID时判断的，参考下：
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/46774210/211781474-8a94c089-d0d4-4381-aa6b-b789309eb3bb.png">

**Comment by CtrlAndZ** [comment]
这是我的完整示例：

应用配置api_v1_views_user_get_user权限：
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/34411788/211784031-a3a849cb-7f58-4513-aa57-901b60e9fc9b.png">

应用ID和密钥，密钥已经生成：
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/34411788/211784326-276d250a-02ab-4b4f-860c-75aa63250653.png">

调用获取用户信息接口，头部传入APP_ID和APP_SECRET对应上面图片中的应用id和接口访问密钥：
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/34411788/211784639-8c60e0f4-aa35-45e1-895e-2c9eb2ae42d7.png">

返回认证失败，这是因为我哪个环节操作不对呢？

**Comment by hanbinloop** [comment]
您好，感谢您的反馈。
请注意APP_ID和APP_SECRET的_应该为-
另外权限的添加和删除时，需要保证celery是启动状态

**Comment by CtrlAndZ** [comment]
> 您好，感谢您的回复。 请注意APP_ID和APP_SECRET的_应该为- 另外权限的添加和删除时，需要保证celery是启动状态

谢谢，将APP_ID和APP_SECRET的_应该为-接口就通了
