### ISSUE TITLE
[Proposal] V2

### ISSUE THREAD

**Issue by RockLi** [longguikeji/arkid#218]
### Goal

TBD

##### 参考文档
1. https://storage.googleapis.com/pub-tools-public-publication-data/pdf/43231.pdf
2. https://storage.googleapis.com/pub-tools-public-publication-data/pdf/44860.pdf
3. https://storage.googleapis.com/pub-tools-public-publication-data/pdf/45728.pdf
4. https://storage.googleapis.com/pub-tools-public-publication-data/pdf/f29b3e764b1122d508b7b53544a3bbadd6cd1101.pdf
5. https://storage.googleapis.com/pub-tools-public-publication-data/pdf/c8da594124dab1f91e6750995e2b7805403b19f1.pdf
6. https://storage.googleapis.com/pub-tools-public-publication-data/pdf/b9b4a09a913e410b7c45f3fbacec4d350e38146f.pdf

#### New Implementation of the Permission Controlling Model

- ACL 
- (H)RBAC 
![image](https://user-images.githubusercontent.com/23496607/92355766-82d8a780-f117-11ea-965a-ac4e645498d4.png)

##### Real-time permissions calculation

实时计算权限接口完全取代定时刷新权限异步任务，权限存储结构需重构
更换算法及数据结构，提高性能的同时降低数据记录的增长速度

#### New Operation Mode: **Proxy Mode**

典型场景，如期望的用户数据存储在其他系统中，如微软的本地AD或者Azure AD或者自有的LDAP中，
仅仅将ArkID以Proxy的模式启用，以便使用ArkID的更多特性，如WEB Based Management Panel, OAuth2 Server等等, 如下图所示: 

    Client <-> ArkID(in Proxy Mode) <-> Upstream idP

#### OpenAPI 

使用openapi-generator生成arkid的多语言SDK
[https://github.com/OpenAPITools/openapi-generator](url)

#### Social Login

- Google
- Github
- 钉钉
- 微信
- 企业微信
- Twitter
- ...

#### User Inventory Provider

支持桥接各种用户数据源，如关系型数据库等。典型的场景为企业拥有自己的账号数据源，但是很难迁移到ArkID的用户模型中，用户可以实现自己的Service Provider接入ArkID，而不破坏原有的企业内部IT架构。

_注意与Proxy Mode的区别。_

#### plugin mode

允许arkid以app的模式加入到django项目中，同时保证与arkid有关的中间件如redis(cache)的启停可配置。
保证插件模式下的arkid无需配置即可使用

#### MFA/2FA
支持二步验证: 短信、邮箱，支持TOTP协议([RFC6238](https://tools.ietf.org/html/rfc6238))

#### 组件拆分

为了更好的服务各种使用场景，需要将组件按功能做进一步合理拆分。
TBD

#### Protocol支持列表

- LDAP
- OAuth2
- OpenID Connect
- SAML2
- CAS Web
- Radius?
 

#### Authentication authorization extension

提高arkid的可扩展性，用户有各种认证授权需求的，例如wifi认证接入等
用户可将自开发的认证授权流程接入arkid扩展模块，使arkid能够灵活支持用户自定义的授权协议

#### Flow Hooks

支持常见的Hook扩展定义能力，如: ```user.login.after: xxx```, ```user.logout.after: xxx``` and etc. 

#### 数据校验、数据绑定节点

TBD

#### Impersonate

TBD

#### Statistics 

基于日志系统（log4j），支持统计分析，如应用级别，接口级别，用户级别等

### Design Documents

1. [V2 API](https://github.com/longguikeji/arkid/wiki/ArkID-V2-API)

**Comment by Oo-RR-oO** [comment]
提高arkid的可扩展性，用户有各种认证授权需求的，例如wifi认证接入等
用户可将自开发的认证授权流程接入arkid扩展模块，使arkid能够灵活支持用户自定义的授权协议

**Comment by RockLi** [comment]
The dev branch of v2 is: v2-dev
