### ISSUE TITLE
通过/oauth/token获取的回复中缺少id_token

### ISSUE THREAD

**Issue by SWerllen** [longguikeji/arkid#226]
请问是bug还是之前查询获取code的操作需要特定的参数？

**Comment by Oo-RR-oO** [comment]
如果是oidc app的话，需要在scope中添加openid字段

**Comment by Oo-RR-oO** [comment]
> 请问是bug还是之前查询获取code的操作需要特定的参数？

如果是oidc app的话，需要在scope中添加openid字段

**Comment by dufeixiang** [comment]
垃圾东西，要开源就做好一点，不要搞一个玩具出来浪费大家时间
