### ISSUE TITLE
user 更新时报错

### ISSUE THREAD

**Issue by longgui-penglei** [longguikeji/arkid#253]
① 报错截图
![image](https://user-images.githubusercontent.com/70128826/112803212-a0fef880-90a5-11eb-9e73-ccb902afb3d3.png)

② 报错信息
![image](https://user-images.githubusercontent.com/70128826/112803433-d86da500-90a5-11eb-8800-3233e2fdc3d6.png)

**Comment by fanhe-lg** [comment]
https://github.com/longguikeji/arkid/pull/255
