### ISSUE TITLE
V2打包部署

### ISSUE THREAD

**Issue by RockLi** [longguikeji/arkid#256]
部署方式:

1. docker-compose
2. k8s

**Comment by notevery** [comment]
arkid v2-dev 使用 mysql 做数据库，migrate失败

**Comment by RockLi** [comment]
fixed in #https://github.com/longguikeji/arkid/commit/8fa91944195e5d0d5e08e34a20ba57d3e2b15459

**Comment by notevery** [comment]
arkidv2 的helm/charts 和 docker-compose部署方式：

https://github.com/longguikeji/arkid-charts/tree/v2-dev
