### ISSUE TITLE
LDAP Arch Design

### ISSUE THREAD

**Issue by welylongguikeji** [longguikeji/arkid#375]

**Comment by luolu-lg** [comment]
为 ArkID2 实现 LDAP v3 协议

**Comment by luolu-lg** [comment]
LDAP Server 选型已完成，经讨论最终选用 ldapjs 库实现 LDAP v3 兼容服务功能

**Comment by luolu-lg** [comment]
LDAP 分工
1、身份源服务
- [ ] 后端API实现: 身份验证与查找用户接口 @guancyxx 
- [ ] ldapjs LDAP Server 实现 @longgui-penglei

2、身份源代理
- [ ] arkid 身份认证代理到 LDAP Server @luolu-lg @fanhe-lg
