### ISSUE TITLE
feat: 第三方登录创建显示问题

### ISSUE THREAD

**Issue by notevery** [longguikeji/arkid#390]
现在创建第三方登录的逻辑是：先随便填一个 id和secret，创建出来之后再编辑才能查看到 URL信息，之后再去gitee填信息获取id和secret；gitee创建第三方应用的时候，需要填 URL，才能生成 id和secret；arkid创建 gitee第三方登陆的时候需要先知道id和secret才能显示出URL：也就是 arkid 和 gitee 总有一个地方是先瞎填。咱们的arkid的URL是固定的，可以在选定type之后就拼出来URL。
![image](https://user-images.githubusercontent.com/12843847/118962419-f1088600-b997-11eb-8c3c-420f46f68491.png)
![image](https://user-images.githubusercontent.com/12843847/118963191-ca971a80-b998-11eb-8883-992fd7f3a637.png)

**Comment by longgui-penglei** [comment]
ok
