### ISSUE TITLE
helm默认安装之后，提示mysql不支持local登录

### ISSUE THREAD

**Issue by markguy** [longguikeji/arkid#488]
这是arkid-web-server 里边的日志
![image](https://user-images.githubusercontent.com/807426/126578385-575eba08-c0e2-4a30-a559-26dd56d4f362.png)

另外再mysql-db容器里边确实也链接补上
![image](https://user-images.githubusercontent.com/807426/126578454-d191a82b-24f6-4e09-9e55-60fbd0b313a6.png)

**Comment by notevery** [comment]
在 mysql-db 中连接方式： `mysql -uroot -p`  回车输入默认密码：root

kubectl get pods    查看pod启动状态shi是否为running：
![image](https://user-images.githubusercontent.com/12843847/126594170-969694da-635e-40d8-8e83-2b0af75d356f.png)
