### ISSUE TITLE
Device

### ISSUE THREAD

**Issue by longgui-penglei** [longguikeji/arkid#499]

**Comment by welylongguikeji** [comment]
https://github.com/longguikeji/arkid/wiki/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C.%E7%A7%9F%E6%88%B7%E7%AE%A1%E7%90%86.%E7%94%A8%E6%88%B7%E7%AE%A1%E7%90%86#%E8%AE%BE%E5%A4%87%E7%AE%A1%E7%90%86
