### ISSUE TITLE
docker-compose启动不起来

### ISSUE THREAD

**Issue by airclear** [longguikeji/arkid#524]
直接clone下来，原样无修改，有两个容器启动不起来

![image](https://user-images.githubusercontent.com/4103690/128803894-617381b8-6b17-4e2a-b2f0-42bcb7bfd164.png)

![image](https://user-images.githubusercontent.com/4103690/128803879-8f4cdae3-aa3a-4080-a733-33d2628efc91.png)

**Comment by learn2s** [comment]
遇到同样的问题，但是已经解决，注意映射的存储卷需要下载对应的内容挂载，be 下面的
