### ISSUE TITLE
权限管理组权限无法展开第二级别以上

### ISSUE THREAD

**Issue by lihang212010** [longguikeji/arkid#713]
![image](https://user-images.githubusercontent.com/38468839/151124835-cc140001-84d4-4280-99bb-e2e09c1abb00.png)

对于三级的组级别在权限管理中无法进行展开

![image](https://user-images.githubusercontent.com/38468839/151124790-43f7e797-6bdc-437f-a50d-c0ec90994938.png)

**Comment by longgui-penglei** [comment]
已处理，谢谢您的反馈。https://github.com/longguikeji/arkid/pull/718#issue-1125464404
